default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rs-security_development

test:
  <<: *default
  database: rs-security_development

production:
  <<: *default
  database: rs-security_development

